apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: coworking-project
  name: coworking-project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: coworking-project
    spec:
      containers:
      - image: sepid/coworking-project:latest
        name: coworking-project
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: DB_USERNAME
      restartPolicy: Always