apiVersion: v1
kind: Service
metadata:
  labels:
    service: coworking-project
  name: coworking-project
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: coworking-project